### ISSUE TITLE
unable to rename database without root

### ISSUE THREAD

**Issue by escoand** [n76/Local-GSM-Backend#10]
On AOSP 5.0 it's not possible to rename the database after creating without root privileges.

**Comment by n76** [comment]
Thats a pain. It may take a fairly large redesign on how I handle data to work around that. It will probably take me a couple of days to think about possible solutions.

**Comment by escoand** [comment]
I use it within my own app like that: https://developer.android.com/training/basics/data-storage/databases.html#WriteDbRow

**Comment by escoand** [comment]
I've renamed the file over USB but it seem to me it's also not readable.

**Comment by n76** [comment]
Looks like sqlite supports table rename. I think I can replace the current create new database file then rename the files when the location process is in a position to close and reopen the database with the following:

Use live database for download but put new data into a new table. Once the download successfully completes, drop old table and rename new table to being the active one.

Busy now on other things so it will probably be a week or so for me to get to this.

**Comment by escoand** [comment]
It seems to work now. Thanks.
