### ISSUE TITLE
F-Droid Build Issue

### ISSUE THREAD

**Issue by BennZoid** [n76/Local-GSM-Backend#102]
Currently the fdroid build is failing as its looking for the tag 'v1.4.17' and the most recent release has the tag '1.4.17' (without the leading v).  

This can be seen here https://f-droid.org/wiki/page/org.fitchfamily.android.gsmlocation/lastbuild_63

I've been awaiting the new build as I have the new style opencellid API key and the current build on fdroid is still 1.4.14.

Would you be able to delete the tag and make a new one with the style fdroid is looking for?

**Comment by n76** [comment]
I think I've got it tagged correctly now.

**Comment by BennZoid** [comment]
Looks good to me.  Thank you!
