### ISSUE TITLE
Truncated log percentage (...,84%, 85%, 100%)

### ISSUE THREAD

**Issue by tomikmar** [n76/Local-GSM-Backend#105]
My download log looks like this:
```
...
085%: Records Read:21048000, Inserted: 474779
085%: Records Read:21049000, Inserted: 474779
085%: Records Read:21050000, Inserted: 474779
085%: Records Read:21051000, Inserted: 474779
085%: Records Read:21052000, Inserted: 474779
085%: Records Read:21053000, Inserted: 474779
info: Records Read:21053802, Inserted: 474779
info: Total Time: 1848401 ms ( 0.088 ms/record)
100%: Creating indicies for faster access.
info: Total Time: 1856647 ms
info: Finished.
```
After 85% there is 100%. I am not sure if some data is missing or it is just incorrect percentage.

Full log: [lacells_gen.log.zip](https://github.com/n76/Local-GSM-Backend/files/1215846/lacells_gen.log.zip)

**Comment by n76** [comment]
Incorrect percentage: Data on the provider's server is in ZIP format file. The file is unzipped, parsed and records added to the on phone database on the fly so we don't really know how big the fully unzipped file is nor how many records (lines) are in the file. The total number of records we use for computing the percentage done is an estimate based on expected unzip expansion amount and it guesses on the large side so the percentages are lower than actual.
