### ISSUE TITLE
Show number of records in database on "Database" screen

### ISSUE THREAD

**Issue by tomikmar** [n76/Local-GSM-Backend#106]
It would be good to show number of records in database on "Database" screen (e.g. below "Last database update"). It would help with debugging - this way it would be easier to check that database was created correctly and is accessible to application.

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
