### ISSUE TITLE
Improve notification while database is created

### ISSUE THREAD

**Issue by tomikmar** [n76/Local-GSM-Backend#107]
It would be good to improve database creation notification:
* show database creation progress (e.g. percentage and records read)
* when database creation takes more than 1h, notification shows only "1h" without minutes

![screenshot_20170810-221238a](https://user-images.githubusercontent.com/5788375/29191068-b52b4b32-7e1c-11e7-804e-8419721166e7.png)

**Comment by ArchangeGabriel** [comment]
The 1h part comes from the system, so nothing can be done here (or you would have to add the duration to the notification text).

**Comment by tomikmar** [comment]
From my point of view (as user) the most important is to have some visible progress what is going on. When background service that update database lose synchronization with user interface, the notification is the only information visible.

If "1h" comes from the system I wouldn't change it, but the first point with e.g. percentage and records read would be useful.

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
