### ISSUE TITLE
v64: Samsung Galaxy S4 + SlimRom 6.0.1: No UnifiedNlp location was provided by the system within 10 seconds

### ISSUE THREAD

**Issue by ProBackup-nl** [n76/Local-GSM-Backend#111]
There is no SIM-card installed in this Galaxy S4.

I have installed UnifiedNlp 1.6.8 `NetworkLocation.apk` because there are no GAPPS here.

Then:
`./adb install org.fitchfamily.android.gsmlocation_64.apk`

Enabled, disabled, and enabled "GSM Location Service" backend, and given it the permissions.

Downloaded Lacells databases with .nl, .be, .de filters (1.5M db entries).

UniefiedNlp Self-Check shows check marks in every (6 pieces) box and:

> UnifiedNlp has no last known location. This will cause some apps to fail.

> No UnifiedNlp location was provided by the system within 10 seconds.

How can I debug the GSM tower location backend?

PS: love to see an `.apk` release distribution without F-Droid.

**Comment by n76** [comment]
You can see what microG/UnifiedNlp is using by:

`adb logcat | grep NlpLocationBackendFuser`

Nearly all logging is disabled on the release version of the backend, but you might see something with:

`adb logcat | grep gsmlocation`

It should be pretty easy to build the APK yourself using Android Studio.

**Comment by ProBackup-nl** [comment]
Thanks for your rapid response and the hints. 

UnifiedNlp uses `org.microg.nlp.backend.apple/.BackendService` and `NlpLocationBackendFuser: Ignoring location update as it's older than other provider.`

It seems that the combination of AppleWifiNlpBackend and LocalGSMBackend results in the first one overriding the latter. After disabling AppleWifiNlpBackend, I do see a little different location in OsmAnd with a larger uncertainty radius (which is as expected) `...acc=500...`.

Apparently "UnifiedNlp" "Self-Check" doesn't provide useable output, to see whether it is able to determine the location.

**Comment by n76** [comment]
Closing as it seems an issue with the UI of UnifiedNlp rather than with this backend.

**Comment by ProBackup-nl** [comment]
@n76 You are right, more a UnifiedNlp issue. Though it would be great if Local-GSM-Backend has some interface that gives an indication that "it works", like cell tower ID's or location coordinates.

Note: Android Studio (3.0.1) doesn't run on Mac OS X 10.9, that is the reason why I can't build the `.apk`. Why not also push the `.apk` as release next to the source code? That saves hassle on the user side.

Note #2: Is there something I can do in return for the development effort?
