### ISSUE TITLE
Hangs at old/earlier GSM tower location.

### ISSUE THREAD

**Issue by ProBackup-nl** [n76/Local-GSM-Backend#112]
```
./adb logcat | grep NlpLocationBackendFuser
12-30 20:14:01.735  2631  2650 V NlpLocationBackendFuser: location=Location[network 51,929016,4,399280 acc=1227 et=+11h3m25s459ms {Bundle[{noGPSLocation=Location[network 51,929016,4,399280 acc=1227 et=+11h3m25s459ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
12-30 20:14:04.224  2631  2642 V NlpLocationBackendFuser: location=Location[network 51,929016,4,399280 acc=1227 et=+11h3m27s940ms {Bundle[{noGPSLocation=Location[network 51,929016,4,399280 acc=1227 et=+11h3m27s940ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
12-30 20:14:06.728  2631  8321 V NlpLocationBackendFuser: location=Location[network 51,929016,4,399280 acc=1227 et=+11h3m30s452ms {Bundle[{noGPSLocation=Location[network 51,929016,4,399280 acc=1227 et=+11h3m30s452ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
```
This location is about 10 kilometer of the current location. I passed that location a few hours ago (±16:00). Since then it seems that Local-GSM-Backend hangs.

SatStat currently shows GSM:
MCC=204
MNC=16
LAC=1514
Cell ID=13638652.

> > Sorry, no one Base Station was found!
> > http://cellidfinder.com/cells

I have disabled Apple-WiFi-Backend for at least 16 hours.

Android 6.0.1 (SlimRom), on GT-I9505 (Samsung Galaxy S4)

--- 
After a reboot SatStat GSM shows:
MCC=204
MNC=16
LAC=1514
Cell ID=13244778

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
