### ISSUE TITLE
Custom database path, no error displayed when invalid path given.

### ISSUE THREAD

**Issue by dragetd** [n76/Local-GSM-Backend#116]
When setting a database directory to a path with no write permissions, Local-GSM-Backend simply downloads the database to the default storage (intern/Android/data/org…gsmlocaltion/files/) instead of showing any error or warning.

The most simple solution would be to show the database path when downloading the database and print an extra warning if it has been reset to the default location because of some issue with the path.

A more elegant solution would be to check the path when it is configured. :)

**Comment by n76** [comment]
Place to check path is in onPreferenceChange() in AdvancedSettingsFragment. Question is what should the action be if the path is invalid?

**Comment by dragetd** [comment]
I was just confused to see my internal storage melting away after I configured a path via pasting it into the config. It was truncated by #118 and only noticed it later.

It is an app for geeks and we do not really need a fancy 'user experience' idea here. ;-) Maybe add the download-database path to the detailed log? If you think that is pointless, feel free to just close this issue.

Maybe when I have more time and dive back into Android Development, I'll return with some ideas + PRs :)

**Comment by bege10** [comment]
For a "quarter-geek" like me showing a file browser dialog would be very helpful, because I don't understand why the entered path on the external SD card doesn't work.

**Comment by JackieHammer** [comment]
configs = YAML.load_file('test/database.yml') ActiveRecord::Base.configurations = configs db_name = ENV['DB'] || 'sqlite' ActiveRecord::Base.establish_connection(db_name) ActiveRecord::Base.default_timezone = :

**Comment by dragetd** [comment]
I belive the PR fixed the issue and this can be closed? If I overlooked something, please say so, then I will reopen. Thank you very much! :)

**Comment by bege10** [comment]
I never had an update of the app and I don't get an error notice if I add a path on external SD-card other than /Android/data/... And that's the only path that works on my phone.

**Comment by dragetd** [comment]
I thought 1.4.22 had the PR included. But checking my installed version 1.4.22, I can confirm that there is not popup for the path or any changed behavior.

I'll leave it up to n76 to decide and close this one. :)

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.

**Comment by bege10** [comment]
Thank you very much for this great tool and for passing it on.

**Comment by dragetd** [comment]
I second that, thank you very much for all your work! <3
