### ISSUE TITLE
Does it interfer with IchnaeaNlpBackend (Mozilla Location Service) ?

### ISSUE THREAD

**Issue by BridouZ** [n76/Local-GSM-Backend#12]
Hey, just installed your backend and I have a question, does your backend interfer with IchnaeaNlpBackend if I select both backend.

I want to submit cell towers and wifi access point for Mozilla and so keep using IchnaeaNlpBackend

Thanks

**Comment by n76** [comment]
Just installed the Mozilla/Ichanea backend from F-Droid and it seems to run without conflict with both my Local-GSM-Backend and with my personal WiFi backend. The location given by the Mozilla backend seems to be less accurate in my area than the other backends I have tried. But I guess more data will make it better.
