### ISSUE TITLE
Custom database path not working

### ISSUE THREAD

**Issue by radasbona** [n76/Local-GSM-Backend#122]
Hi,
i installed gsmlocation as systemapp.
Everything works well, except moving the database on the on the system partition. 

I change the path so /system/priv-app/org.fitchfamily.android.gsmlocation/lib and start a new download. The custom path has been ignored. 
I moved the lacells.db, the files was not recognized.

What did i wrong? The app should have write permissions in it's own folder.

**Comment by n76** [comment]
/system is normally mounted read only so it would not be possible for the app to write data anywhere on it.

"Own folder" in the case of Android would be a folder in /data.

**Comment by radasbona** [comment]
🤔 Ok, i see.
But even a moved lacells.db is not used with read permission.

Anyway, was just an idea the save /data space.
