### ISSUE TITLE
Minor Bug: Status Bar stops at 27.9% 

### ISSUE THREAD

**Issue by rapht0r** [n76/Local-GSM-Backend#123]
Status bar stops at 27.9% when creating the database from both sources at once (Mozilla and OpenCell ID). 
For me this occured when I had the additional info expanded.
The database creation of course continues, its only the status bar that hangs.
Also theres no further log entries.

Also the log says the file length is "959637849" but the line below where it says somethin like "parsed entries" stops at "40664020" not sure if the length and number of entries is simly a different thing or this is also a bug? 
Edit: Also the status bar resumes at 50% when the second source is downloaded and then works with no issues till the end

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
