### ISSUE TITLE
Download doesn't finish when put in background

### ISSUE THREAD

**Issue by miquecg** [n76/Local-GSM-Backend#124]
Hi,

I cannot finish downloading cell tower data if the app goes to background. That is:
- When switching to another app with "recent apps" button
- If the phone screen suspends after some time
- Or if I manually lock the phone

I have to say that this doesn't happen just immediately after locking the phone for example. Sometimes it's after a few minutes or maybe instantly when switching to another app...

All required permissions are granted. I'm running LOS (16) for microG (0.2.6.13280). App version is 1.4.22.

I have to check also if "showing details" of the download does make any difference in this behaviour.

**Comment by miquecg** [comment]
Confirmed today again with microG version 0.2.7.17455. I've left the phone downloading cell tower data and after some time with the screen off I've checked it and the download had been aborted. Also, I can confirm that "showing details" does not make any difference.

The only strange thing I've noticed is that progress percentage gets stucked at ~27% although records are being read and inserted. After some time the progress jumps to ~50% when parsing data of the second provider. See issue #123.

**Comment by n76** [comment]
As noted in the notice at the top of this project's README, this is in maintenance mode only.

There is a fairly substantial set of changes to the background download of data in this backend that exceeds my current level of effort on this project. If a pull request is given to me that addresses this issue I will merge it. But lacking a change request, this issue will not be fixed.

**Comment by Iey4iej3** [comment]
Is it possible to use Android's downloader to download instead of manually implement one? It seems to me that Doze mode makes things harder.

**Comment by miquecg** [comment]
Closing. Wont-fix

**Comment by Lee-Carre** [comment]
The workaround I use is
1. force the display to always-on (with developer options, or via an app)
2. trigger a update
3. leave the phone alone (with the backend's UI as the foreground app) for the 30-45 minutes it needs to complete
