### ISSUE TITLE
intent/interface for on-the-fly updates to the database?

### ISSUE THREAD

**Issue by IzzySoft** [n76/Local-GSM-Backend#128]
I'm using TowerCollector to contribute to OpenCellId and Mozilla. It would be pretty nice to feed the collected data directly to the LocalGSMBackend database as well, to have it instantly available. The developer of TowerCollector would be willing to implement that (see [this issue](https://github.com/zamojski/TowerCollector/issues/65)); but to do so, they'd need a way to hand the data over.

Is there any intent or other interface available with LocalGSMBackend that would accept new data? If not, could you provide such – or what approach would you recommend?

Thanks in advance!

**Comment by n76** [comment]
As noted on the README, this backend is mostly in maintenance mode. If someone gives me a pull request with an intent implemented for adding data to the database, then I will consider it.

**Comment by IzzySoft** [comment]
Thanks! And yes, I'm aware you've switched your focus to DejaVu. I'm no Android dev, so I cannot make that PR; hopefully someone else will.

Forgive my ignorance, but would directly updating the `lacells.db` work, and your backend would use those data? The database is located on the SD card, so the update itself might be technically possible (given the `(READ|WRITE)_EXTERNAL_STORAGE` permission).

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
