### ISSUE TITLE
gsmlocation points to old URL

### ISSUE THREAD

**Issue by n76** [n76/Local-GSM-Backend#132]
Received by email:

> First, thank you for this finely functional backend.
> 
> issue:
> The MLS url for its cell networks database is now https://d2koia3g127518.cloudfront.net/export/
> 
> and the "update database" option fails with an 'Unable to resolve host' error.
> 
> Would you release an update that allows the user to edit this url, avoiding further updates for this issue?
> 
> Thanks again.

**Comment by deveee** [comment]
I was too lazy to make a config file for that url, I made simple shell script that is easily configurable though. If someone is interested in it, you just need terminal emulator with sqlite installed and you should change MCC_FILTER to you country code.

```
#!/bin/sh

# Country codes
# https://en.wikipedia.org/wiki/Mobile_country_code

export RADIO_FILTER="GSM|UMTS|LTE"
export MCC_FILTER=260
export DATE=`date -u "+%Y-%m-%d"`
export URL="https://d2koia3g127518.cloudfront.net/export/MLS-full-cell-export-${DATE}T000000.csv.gz"
export TMP_FILE_CSV="./MLS-full-cell-export-tmp.csv"
export TMP_FILE_DB="./MLS-full-cell-export-tmp.db"
export OUT_FILE="/storage/emulated/0/Android/data/org.fitchfamily.android.gsmlocation/files/lacells.db"

rm -f "$TMP_FILE_CSV"
rm -f "$TMP_FILE_DB"

wget -qO- "$URL" | gunzip                                  \
                 | egrep "^($RADIO_FILTER),($MCC_FILTER)," \
                 | cut -d"," -f2-10                        \
                 | sed 's/$/,-1/' > "$TMP_FILE_CSV"

if [ -s "$TMP_FILE_CSV" ]; then
    sqlite3 "$TMP_FILE_DB" "                              \
        CREATE TABLE cells(mcc INTEGER,                   \
                           mnc INTEGER,                   \
                           lac INTEGER,                   \
                           cid INTEGER,                   \
                           unit INTEGER,                  \
                           longitude REAL,                \
                           latitude REAL,                 \
                           accuracy REAL,                 \
                           samples INTEGER,               \
                           altitude REAL);                \
                                                          \
        CREATE INDEX _idx1 ON cells (mcc, mnc, lac, cid); \
                                                          \
        CREATE INDEX _idx2 ON cells (lac, cid);           \
    "

    sqlite3 "$TMP_FILE_DB" ".mode csv" ".import $TMP_FILE_CSV cells"

    mv "$TMP_FILE_DB" "$OUT_FILE"
fi

```

**Comment by sillyseb** [comment]
Hi deveee,
thanks for your great shell script as a makeshift solution!
Sadly, it only seems to work with one MMC: Adding further MCCs like so "MCC_FILTER=260,238" doesn't increase the tower-count in the database as reported by the backend in the configuration of microg.
Can you help?
Thanks, Seb.

P.S.: I'm also wishing/hoping for an update with a user-editable URL.

**Comment by deveee** [comment]
I just checked and MCC_FILTER="260|238" works fine.

**Comment by sillyseb** [comment]
Fantastic, that works great. Thanks deveee!

**Comment by deveee** [comment]
@n76 I know that you are focused on Dejavu currently. Are you plainning to fix it, or maybe should I ask on fdroid to patch it? Because at least updating the url is trivial and without database the apk is kinda useless.

**Comment by n76** [comment]
Actually, I am focused on things other than Android.

I just pulled in a PR that looks like it updates the Mozilla URL and allows the user to update it for themselves if needed. However when I fired up Android Studio for the first time in over a year it failed to compile. Not due to the changes themselves but because the Google API compatibility stuff could not be found. I am still futzing with that to see how to actually get the thing compiled. I'd rather not put a release tag on it (which F-Droid needs) until/unless I can compile it. It would be better if I could actually run it too but I am not using an Android phone at present.

If there is someone who is willing to take over this project, I would be more than willing to assist them in doing what ever is needed to make them the owner.

**Comment by n76** [comment]
I am re-opening this pending a good build.

**Comment by deveee** [comment]
You need old java for old gradle, eg.
```
#!/bin/sh

cd "`dirname "$0"`"

export ANDROID_HOME=/mnt/data/Dokumenty/android/android-sdk

if [ -f "/usr/lib/jvm/java-8-openjdk-amd64/bin/java" ]; then
    export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    export PATH=$JAVA_HOME/bin:$PATH
fi

./gradlew assembleDebug

```
Or maybe I can increase gradle version later.

**Comment by IzzySoft** [comment]
@sillyseb take a look at [FastLacellsGenerator](https://github.com/sobrus/FastLacellsGenerator) which uses multiple sources (MLS, OpenCellID and Radio) and merges them. I'm using that for years and am very satisfied with it. Also easily configurable to the networks you're interested in.

@n76 it seems like @deveee [just volunteered](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7923). If you give your blessing, that would help a "seemless update" for current users (disclosure: I'm one of the F-Droid maintainers – and we have the policy that if someone wants to take-over an existing packageName while the original "owner" is still around, a "transfer of ownership" should be confirmed).

**Comment by n76** [comment]
@IzzySoft I have had some correspondence with @deveee and am more than willing to hand this project over to him.

I guess that will make the official repository be https://github.com/deveee/Local-GSM-Backend I will make one more push to this repository to update the README.md file to indicate the change.

Can you update what ever is needed on the F-Droid side to start building from releases in that repository?

**Comment by IzzySoft** [comment]
Thanks @n76 – that makes it easier for all of us! And if you follow my above "volunteer" link you can see that @deveee already opened a merge request against fdroiddata to implement exactly those changes: updating all relevant URLs plus adding his latest build.

Great idea to update ReadMe on both sides (especially here, so users feel safer knowing all's in order). Once the transfer is through (and the update hit the index plus the index the F-Droid website, so the new URLs are propagated), you might even consider archiving this repo here, so you don't get "nagged" anymore.

Before you do that, let me thank you again: I'm a long-time user of your app and really appreciate it. Thanks for all the effort and time you put into it – and thanks to @deveee for keeping the app alive!

**Comment by deveee** [comment]
@n76 I uploaded it to gitlab https://gitlab.com/deveee/Local-GSM-Backend and already released new version with mozilla url fix, so that it can be updated on fdroid. Maybe I should remove the github fork to make it clear that main repo is on gitlab. And I already opened merge request on fdroid that updates package metadata and adds new version.

**Comment by IzzySoft** [comment]
> And I already opened merge request on fdroid that updates package metadata and adds new version.

Which was already merged by a packager :smiley:

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
