### ISSUE TITLE
Backend Doesn't work with unifiednlp with GAPPS

### ISSUE THREAD

**Issue by BridouZ** [n76/Local-GSM-Backend#14]
Currently not1working with the newly unifiednlp (which doesn't require Gapps deletion)

**Comment by n76** [comment]
Can you get me the version numbers of the software you are using and a logcat? Thanks!

(Has the new gapps compatible version of UnifiedNLP shown up on F-Droid yet? That is where I get mine from and I am showing that component as up to date on my phone.)

**Comment by BridouZ** [comment]
Oh, I think I understand why it's Not working. I live in france so I have to change mcc filter to 208 (number for france ). Am I right ?

**Comment by n76** [comment]
Yes, according to http://en.wikipedia.org/wiki/Mobile_country_code#F the mobile country code for France is 208 so if that is where you are that is the code you should use.

**Comment by BridouZ** [comment]
Fixed, thanks
