### ISSUE TITLE
Compatibility with Jelly Bean?

### ISSUE THREAD

**Issue by nuntius35** [n76/Local-GSM-Backend#15]
Is there a technical reason for *android:minSdkVersion="18"* in the manifest? I wanted to download the app from F-Droid for a Jelly Bean device.

**Comment by n76** [comment]
I thought I was making a call to an API that required SDK 18 or higher. But at the moment I don't see it. I've just made a build with the minimum API set to 16 and put it at https://dl.dropboxusercontent.com/u/19663978/android_apps_gsmlp-debug.apk

If you could check that it works okay I would appreciate it. If it does, I'll bump the version number and push it to GitHub.

**Comment by nuntius35** [comment]
Thank you! I downloaded your build and generated a database on the device with both data from OpenCellId and MLS. Then I checked that it works as a location provider. There were no problens for me.
