### ISSUE TITLE
Use plain OpenCellID / MLS format for database?

### ISSUE THREAD

**Issue by wvengen** [n76/Local-GSM-Backend#20]
With OpenCellID and Mozilla Location Service using the same CSV format, why don't we use the same database format? That would be clearer for everyone, I guess.

Not sure if backwards-compatibility would be an issue, e.g. with lacells-creator and [AIMSICD](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector) recently [supporting lacells.db](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/467) too.

**Comment by n76** [comment]
You would like all fields in the OCID/MLS CSV file to be stored in the lacells.db?

The backward compatibility issue would be that the naming is a little different but that could be worked around by having a transition period where old lacells.db field names and OCID/MLS field names are duplicated.

How would you handle fields like "created" and "modified" when merging data between OCID and MLS?

From my point of view with an older phone with no SD card is with database storage. I'd like it to be kept to a minimum and even the current schema has more fields than the GSM backend really needs.

**Comment by utack** [comment]
I don't see the point in making the database readable by humans with no extra functionality and more storage consumption.

This might already be too OT and go in a seperate issue:
Perhaps even go the other way and compress it in some way.
For example generate a [mnc].db for every mnc and remove the endless duplications in the database itself or compress it in some way, since the current CPU time the backend uses is negligible and the storage definitly not.

**Comment by wvengen** [comment]
@n76 The use-case I have in mind is that there are more applications appearing that need OpenCellID/MLS data, and it would be great if we could have a database on the phone in one place that all could use. You do have a point when only local-gsm-backend is present, having only data present that is used by it, is more space-efficient.

@utack I'm not so interested in human readability, but usage of cell-data by multiple applications. Having a clear naming scheme makes that easier on all sides.

Having brought up this issue here, perhaps this is something that needs more investigating of what the needs exactly are.

(Feel free to close, or leave it open if you want others to join in.)

**Comment by n76** [comment]
I can see where multiple apps/projects could find a local (on phone) cell tower database useful. And you certainly don't want to be using up storage for duplicate or nearly duplicate information in that quantity. But I think in that case the schema and management of the database should not be tied to a specific microG unifiedNLP backend.

If a standard exists, or we can come up with such a standard as a separate project, then it would make sense to change the Local-GSM-Backend to use that new database.

I would love to remove the database creation software from the backend and that would make sense as it would be more logical to have the database creation and maintenance separate from the various users. Why would someone want to install unifiedNLP and Local-GSM-Backend to get on-phone database creation if they only wanted the database for some other app?

I think that a on-phone app to create and manage the database is necessary even if it is slow: There are enough potential users who are not tech savvy enough to run scripts on a PC for this purpose. Of course off phone tools are great and should be available but the novice should be able to simply get an app from someplace like F-Droid and click on a button.

**Comment by wvengen** [comment]
Hmm it didn't cross my mind that Local-GSM-Backend could use a standard database, if one would appear. Good point :)

I like the idea of a separate cellid database app. With an app-store-intent the app could even be installed easily from within a consumer of the cellid database.

**Comment by n76** [comment]
If one wanted to get fancy, a cell database app could provide a lookup service for clients like the Local-GSM-Backend so the users would not need to actually deal with file location, permissions, multiple accessors, etc.

I would think the project would require:
1. Definition of the database schema
2. User app access method (direct file I/O vs request to DB service)
3. On-phone app to manage database
4. Sample app to show how to use database
5. Off-phone utilities that might make the database faster than the on phone app can.

**Comment by wvengen** [comment]
:+1: (And now for some extra spare time.)

**Comment by n76** [comment]
If/when Android-IMSI-Catcher-Detector makes their on-phone database available, maybe I will consider using it instead. But until then, I'm closing this issue.
