### ISSUE TITLE
localgsmnlpbackend doesn't give location

### ISSUE THREAD

**Issue by takiainen** [n76/Local-GSM-Backend#30]
I cannot get location with localgsmnlpbackend. My phone is Oneplus one and i've tried different Lollipop based roms (Exodus,AICP,Blisspop,SlimLP) without success. Stock settings, no GAPPS.

Privacy guard show that localgsmnlpbackend has asked location several hundred times (and always allowed), but I localgsmnlpbackend never show up on "settings --> location: recent location requests" -list. 

Wifi Backend however shows up on that list and also gives me location with Osmand or SatSat.

Where's the problem?

**Comment by n76** [comment]
Can you get me a screen shot showing the configuration settings for local-GSM-backend?

Debug logging is normally off on the backend but I can get you an APK with it enabled so that we can use logcat to see what is happening if it is not obvious in the settings.

**Comment by n76** [comment]
A build of version 0.9.3 with debug logging enabled is at https://www.dropbox.com/s/vmj70d6janarj2y/Local-GSM-Backend_0_9_3.apk?dl=0

It is signed by me so you will have to remove any version signed by others (like F-Droid) to install. Once installed, you can use something like:

adb logcat | grep gsm-backend

On a Unix computer to display the log entries it generates. There is probably some equivalent way to do that on Windows but I don't know what it is.

**Comment by takiainen** [comment]
Something strange today: after installing your debug backend, I first didn't get gsm based location, then after moving to another town, I suddenly got a location. But then, after reboot, I no longer get gsm location despite being at same place. 

Here is the logcat, I'm not sure if it shows the events before the reboot, when things worked for a moment. 

D/gsm-backend-service( 6212): Starting location backend
D/gsm-backend-service( 6212): Binder OPEN called
D/gsm-backend-service( 6212): Starting reporter thread
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-database( 6212): Attempting to open database.
D/gsm-backend-database( 6212): DB Cursor empty for: mcc=244, mnc=5, lac=21800, cid=350209
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onServiceStateChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellLocationChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellInfoChanged:  null position
D/gsm-backend-service( 6212): Binder CLOSE called
D/gsm-backend-service( 6212): Starting location backend
D/gsm-backend-service( 6212): Binder OPEN called
D/gsm-backend-service( 6212): Starting reporter thread
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-database( 6212): Attempting to open database.
D/gsm-backend-database( 6212): DB Cursor empty for: mcc=244, mnc=5, lac=21800, cid=350209
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onServiceStateChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellLocationChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellInfoChanged:  null position
D/gsm-backend-service( 6212): Binder CLOSE called
D/gsm-backend-service( 6212): Starting location backend
D/gsm-backend-service( 6212): Binder OPEN called
D/gsm-backend-service( 6212): Starting reporter thread
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-database( 6212): Attempting to open database.
D/gsm-backend-database( 6212): DB Cursor empty for: mcc=244, mnc=5, lac=21800, cid=350209
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onServiceStateChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellLocationChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellInfoChanged:  null position
D/gsm-backend-service( 6212): Binder CLOSE called
D/gsm-backend-service( 6212): Starting location backend
D/gsm-backend-service( 6212): Binder OPEN called
D/gsm-backend-service( 6212): Starting reporter thread
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-database( 6212): Attempting to open database.
D/gsm-backend-database( 6212): DB Cursor empty for: mcc=244, mnc=5, lac=21800, cid=350209
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onServiceStateChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellLocationChanged:  null position
D/gsm-backend-telephonyHelper( 6212): getAllCellInfoWrapper() returned nothing, trying legacyGetCellTowers().
D/gsm-backend-telephonyHelper( 6212): getNeighboringCellInfo() returned null or empty set.
D/gsm-backend-telephonyHelper( 6212): getTowerLocations(): No tower information.
D/gsm-backend-service( 6212): onCellInfoChanged:  null position
D/gsm-backend-service( 6212): Binder CLOSE called

**Comment by n76** [comment]
Looks like your phone, like mine, does not report adjacent cells so it can only use the location of the cell tower it is connected to which is mcc=244, mnc=5, lac=21800, cid=350209

However that tower is not in your database. Querying the Open Cell ID database, I see it is missing from there. And looking at the latest database from Mozilla, I see it is missing from there too.

I suspect your spotty operation is because only a few towers in your area are mapped and the local GSM backend will only return a location if the tower you are connected to exists in the database.
 
It seems that the cell towers in your area are not well mapped. I suggest that you use either an app from OpenCellID at http://wiki.opencellid.org/wiki/Data_sources and/or the Mozilla app at https://location.services.mozilla.com/apps to contribute to those projects. Once you have contributed those cell tower locations to one or more of those projects you should be able to download a new database to your phone and have this backend work.
