### ISSUE TITLE
doesn't clean up

### ISSUE THREAD

**Issue by yepyepyep4711** [n76/Local-GSM-Backend#31]
Hi again,

I don't know whether this only happens in cases of failed downloads, or always, but I've just found out my hidden folder .nogapps was clogging my storage because it was full of files generated by this backend. They go in pairs with the following names:
new_lacells-ninetotenfiguesnumber.db and
new_lacells-sameninetotenfiguesnumber.db-journal
some have the dash after lacells, some don't.
I've deleted all of them and left only lacells.db, that saved me nearly 7GB.
Then I updated the db using the app, now I have:
lacells.db.bak
lacells.db
lacells_gen.log

So if it doesn't rotate backups but just piles them up (which I can't test now because of the one day limit for downloading the cells-db) you might want to change this.

Best

**Comment by n76** [comment]
There is some logic that attempts to clean up from failed downloads but obviously is not working for you. In a couple of error cases there should be a stack trace in logcat. Have you seen that? It might help me determine where the clean up should have occurred but did not.

Do you have a way of forcing this issue so that I can test prior to releasing a new version?

**Comment by yepyepyep4711** [comment]
well I could do another update and see what happens. Do I need to do something to make sure we have a log afterwards? Also, at what level do you want me to log? I'll be using catlog to do this

**Comment by n76** [comment]
Not sure what I am looking for but in a couple of places where it might not be cleaning up after an error there is an e.printStackTrace(); statement. That should show up in logcat and give me a place to focus on. In those cases there is also a log to the screen, like other progress reports, so a screen capture would be helpful too.

**Comment by yepyepyep4711** [comment]
Here's the screenshot ![screenshot_2015-08-13-18-24-02](https://cloud.githubusercontent.com/assets/10447816/9255432/9d23f80c-41e9-11e5-9b62-91a3d3197d77.png)
it seems something else broke this time. Do you still want the log? It's half an MB and there's no e.printStackTrace(); statement in it. I'd need a way to send it to you if you want it
If checked the db file, it hasn't been updated, even though the screenshot says it's inserting towers. On the other hand, no leftover files are present. Only the db, the backup, and the log

**Comment by yepyepyep4711** [comment]
would love to test and close, but can't update because of https://github.com/n76/Local-GSM-Backend/issues/29

**Comment by yepyepyep4711** [comment]
thanks for the compatibility fix, that's great!
It took me many tries, because the download kept breaking up (resuming. Now I have a log that seems to say everything went fine, but if I look at the files in the folder, the only one that has been updated is the log. Here it is. Both the db and it's backup have the old dates. The temp files *have* been cleaned though. First I saw them and then they were gone.
MCC filter: 208,214,268,272,234,206,270,262,228,222,204,232,230,260,231,216,202,293,219,218,284,226,286,278,280
No MNC Filters, assume all networks
Getting Tower Data From Open Cell ID. . .
URL is http://opencellid.org/downloads/?apiKey=74fb87f8-e318-47ca-b0a7-ec1299341417&filename=cell_towers.csv.gz
Content length = 193050505
Records Read: 8182659, Inserted: 4065773
Total Time: 1684429 ms (0.206ms/record)
Getting Tower Data From Mozilla Location Services. . .
URL is https://d17pt8qph6ncyq.cloudfront.net/export/MLS-full-cell-export-2015-10-15T000000.csv.gz
Content length = 371754442
Records Read: 15990798, Inserted: 5607970
Total Time: 2946312 ms (0.184ms/record)
Creating indicies for faster access.
Cleaning up temp files.
Total Time: 8627603ms
Finished.

**Comment by n76** [comment]
Your log shows no errors. . . So if the DB dates are still old then an error is occurring which is not being logged. I'll look into it, if nothing else to add some more logging to help figure out the issue.

**Comment by yepyepyep4711** [comment]
hi @n76, thanks for the new build. I'm now on 1.0.4. I haven't noticed additional logging, but something *is* happening. The log looks good (see below). The app tells me my db is from Nov 26. But now I have three. The .db (previous db), the .db.bak (the one before that) and the .db.new (with the date the app is showing). Look at the screenshot below. Is everything as it should be? Note that I have reduce the number of MCCs, so the db is smaller

MCC filter: 206,262,208,270
No MNC Filters, assume all networks
Getting Tower Data From OpenCellID. . .
URL is http://opencellid.org/downloads/?apiKey=74fb87f8-e318-47ca-b0a7-ec1299341417&filename=cell_towers.csv.gz
Content length = 197056714
Records Read: 8340278, Inserted: 1747925
Total Time: 1243022 ms (0.149ms/record)
Getting Tower Data From Mozilla Location Services. . .
URL is https://d17pt8qph6ncyq.cloudfront.net/export/MLS-full-cell-export-2015-11-26T000000.csv.gz
Content length = 411753998
Records Read: 17677358, Inserted: 2019141
Total Time: 2579633 ms (0.146ms/record)
Creating indicies for faster access.
Total Time: 4129576ms
Finished.
![screenshot_2015-11-26-17-11-53](https://cloud.githubusercontent.com/assets/10447816/11460073/a10d221c-96e5-11e5-9a6e-a45e8a0fe8e3.png)

**Comment by n76** [comment]
For a short period of time there should be three files as you've seen. The download code (or offline db generation script) put a .db.new file on the phone. The next time the operational part of the backend is asked to return a location it checks to see if there is a .db.new file and if so moves the current db to db.bak and then db.new to db.

So if you use some app that requests a location you should see the db.new file be moved to .db and the old db file moved to db.bak (and the old db.bak removed).

**Comment by yepyepyep4711** [comment]
yep. I did just that. It did just what you said. Thanks.
Sadly, it seems I now have the problem that my legacy NLP is not running it the background, but only if I open the app and push "configure location backends". Probably why I still had the three db after several days. I guess I'm going to try reinstalling manually, as the last upgrade was done using f-droid.
