### ISSUE TITLE
move /sdcard/.nogapps to /sdcard/Android/data/org.fitchfamily.android.gsmlocation

### ISSUE THREAD

**Issue by bharat226g** [n76/Local-GSM-Backend#33]
Since the lacells database sharing between other apps is insignificant,
Please move /sdcard/.nogapps to /sdcard/Android/data/org.fitchfamily.android.gsmlocation/ 

Doing so eliminates the READ/WRITE_EXTERNAL_STORAGE permission and keeps things organized.

**Comment by agilob** [comment]
I implemented it once for android-imsi-catcher-detector where code is on GPL, my PR with changes is [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/f3e8161539dd6b98c0d4ea879a103632ed445a02#diff-27a3acf59f47a7b2dd729148fd7467dfR644). If you want I can do it over the weekend, it's just one method to setup in main activity in onCreate method and use this location in other areas of code.

**Comment by n76** [comment]
@agilob I am a bit busy with other things right now so if you'd like to develop the patch, go ahead. It takes less time to review and accept a change than to develop it. All the paths are located in appConstants. Probably the easiest way is to instantiate that with a method that takes the context and then set the DB_DIR variable as desired.

**Comment by agilob** [comment]
sure. thanks for info.

**Comment by agilob** [comment]
Well, it's more difficult than I expected, basically 3/4 of the application must be rewritten to implement this.

**Comment by UnknownUntilNow** [comment]
Can be closed.

**Comment by n76** [comment]
read/write external storage permission will be dropped after next release to allow for most users to transition cleanly.

**Comment by juneyao** [comment]
if read/write external storage permission is dropped, would it be possible to move data to external sdcard/data/org.fitchfamily.android.gsmlocation/files?

**Comment by UnknownUntilNow** [comment]
No

**Comment by juneyao** [comment]
most phones still come with barely enough storage for apps (16gb internal sdcard). lacells database is huge, so the ability to place it on the external sdcard is essential. is there any workaround for this other than symlinks? any old version supporting it?
