### ISSUE TITLE
database creation failed on android 6

### ISSUE THREAD

**Issue by takiainen** [n76/Local-GSM-Backend#40]
Please see the attached screenshot.
![tmp_10121-screenshot_20151125-220829747108237](https://cloud.githubusercontent.com/assets/13743305/11408341/1d63ee36-93c1-11e5-865d-b4a5c1768c5e.png)

Ive got oneplus one running Omni rom 6.0 marshmallow.

**Comment by takiainen** [comment]
It was a permission issue. Sorry, i will close this issue now.

**Comment by hogbush** [comment]
Because of my mistake, versions 1.0.2 and 1.0.3 don't work on Marshmallow unless you explicitly enable all permissions in the settings. Version 1.0.4 handles runtime permissions properly and should work well.
