### ISSUE TITLE
Per country import not robust

### ISSUE THREAD

**Issue by n76** [n76/Local-GSM-Backend#47]
v1.3.0 implements loading MCC filtered data from the lacells project run by @wvengen however import fails if any of the MCC codes requested are not found in the repository and a check is not made before starting the database generation. So quite some time can be spent downloading good MCC data before the non-existent file is requested.

If using the by MCC code data from lacells, the backend should check that all desired files exist before starting the database generation.

**Comment by UnknownUntilNow** [comment]
That's not correct. At https://github.com/n76/Local-GSM-Backend/blob/master/app/src/main/java/org/fitchfamily/android/gsmlocation/async/DownloadSpiceRequest.java#L139, during building the URL list (before any download) it throws an Exception if the MCC is not available (because it only knows the number of records for an MCC if it is available).

**Comment by n76** [comment]
Hmmm. That should work. I did have it fail a couple of times when it had processed about half the files/MCC codes I had specified. I finally gave up. Maybe there is a weakness in the logic for opening a stream, a transient error, which caused my problems.

**Comment by UnknownUntilNow** [comment]
At which MCC failed it?
What does the logfile say?

**Comment by n76** [comment]
Seems to be failing at different places. Most recent attempt (deleting the myriad progress report lines) shows:

  info: MCC filter: 316,334,312,311,310
  info: No MNC Filters, assume all networks
  info: URL is [https://wvengen.github.io/lacells/lacells-mcc_334.csv] (none)
  info: Content length = -1
  info: Records Read:306800, Inserted: 306786
  info: Total Time: 80997 ms ( 0.264 ms/record)
  fail: 90 >= 90
  info: Total Time: 81200 ms
  info: Finished.

**Comment by UnknownUntilNow** [comment]
This happens at https://github.com/n76/Local-GSM-Backend/blob/master/app/src/main/java/org/fitchfamily/android/gsmlocation/async/DownloadSpiceRequest.java#L329 when there are not very much records (compared to other used sources). I'm going to fix it.
