### ISSUE TITLE
[Enhancement] Determine more precise location by evaluating all cell towers in range

### ISSUE THREAD

**Issue by utack** [n76/Local-GSM-Backend#5]
Currently the main program seems to look up the cell tower the phone is connected to and determine the position based on that.
Idea for an enhancement:
The phone knows all cell towers in range. Combined with the precision from the database a location where all towers in range overlap should be a lot more precise than the location based on one tower.

**Comment by n76** [comment]
The backend attempts to get all towers and do a position estimate based on all of them. It first tries using the getAllCellInfo() method in the telephony manager and if that returns null then it calls getCellLocation() and getNeighboringCellInfo().

However on my Samsung Galaxy Nexus the getAllCellInfo() and getNeighboringCellInfo() methods always return null. Based on some web searches I have made, it is my impression that this is a common issue with most if not all Samsung phone models.

What make and model phone do you have? If you have one where those calls work then you could help me verify operation when more than one cell tower is in range.

**Comment by utack** [comment]
I am using this on a Sony Xperia Z1 running Cyanogenmod 11. If you have a debug apk, I would really like to find out if it works fine. However I doubt it, as the location can be off up to 500m in a city area.

**Comment by n76** [comment]
There may be a separate error in my calculation of accuracy. :)

For the moment, lets see if your phone is properly implementing the two calls and I am properly calling them. I have put a debug build with a little extra logging at https://dl.dropboxusercontent.com/u/19663978/android_apps_gsmlp-debug.apk

You should be able to install it (might have to remove the one from F-Droid first if that is where you got yours) and look at logcat. I typically change the location settings to "Battery Saving" and set unifiedNLP to only have the one back end I am debugging but strictly speaking that should not be required.

My install and debug monitoring are as follows:
    adb install -r android_apps_gsmlp-debug.apk
    adb logcat | grep gsm-backend

**Comment by utack** [comment]
It does indeed work on my device. I will look at the calculations when I find time, but today the precision was a lot better. Maybe my phone was really connected to some strange remote tower before

**Comment by n76** [comment]
If/when you have a chance, could you post some of the logcat for me? I'd like to review the operation of the code when information about multiple cell towers is available. Thanks!

**Comment by n76** [comment]
Closing as I haven't been given logcat files to pursue this further.
