### ISSUE TITLE
Allow background generation of database

### ISSUE THREAD

**Issue by utack** [n76/Local-GSM-Backend#51]
When "minimizing" the app a running database generation is interrupted and has to be restarted from the beginning.
Please allow it to continue in the background, because the current way it does not allow using my phone for anything for quite some time.

**Comment by n76** [comment]
Recent versions should perform background generation of the database. If/when it fails to do so, could you use a file explorer to grab the log file at /sdcard/.nogapps/lacells_gen.log and forward it.

**Comment by UnknownUntilNow** [comment]
Database generation happens in background since <https://github.com/n76/Local-GSM-Backend/commit/618862b9b8f7e4e3e173e90bd3b7b1e47f23291f> (version 1.1.0). In some rare cases the progress isn't shown/ the downloading is interrupted after reopening.

If you can reproduce this, please tell how.

**Comment by utack** [comment]
I now have a logcat of the problem, what to grep for to filter everything relevant?

**Comment by UnknownUntilNow** [comment]
Download
SpiceRequest
SpiceService

**Comment by n76** [comment]
UI might have issues displaying the progress, but database generation now occurs in background.

**Comment by utack** [comment]
You are right, generation works even without display

**Comment by licaon-kter** [comment]
you get a call or you open another app by mistake or the moon aligns with Venus, you can't do anything at all 'cause the download is cancelled.

Now, this issue says it works in the background, the progress is not shown, the download REstarts from 0% if I press download.

How can I check that it actually works in the background?

**Comment by n76** [comment]
logcat is your friend to see if it is downloading in the background.

**Comment by licaon-kter** [comment]
Ok, now I can see, I got a text-less notification with a correct icon (I can try to block the notification so I now see it's the right app). Also, luckly I do have a network statusbar info thing that shows a transfer actually taking place, so yeah it's working.

Now should I open separate issues for... ?
* add info text to notification `Database download in progress...`
* add the actual info in notification text (XXX cells etc)
* app picking up background downloading and not letting me to press download yet again (at least) say `Database download in progress...`

**Comment by n76** [comment]
I've been mentally using https://github.com/n76/Local-GSM-Backend/issues/65 as the issue to track those three things. And the way I'd like to make it work is to have the download status just show up if it is downloading (cells read, saved, with progress bar, etc.)
