### ISSUE TITLE
fail: unknown format (magic number a0d)

### ISSUE THREAD

**Issue by vanitasvitae** [n76/Local-GSM-Backend#55]
Hi
The download often fails due to the error mentioned in the title. Sometimes it works again after a reboot. What causes this error? I try to download from OpenCellID and Mozilla.

**Comment by n76** [comment]
There should be a log file named lacells_gen.log at either /sdcard/.nogapps/ (before v1.3.3) or /sdcard/Android/data/org.fitchfamily.android.gsmlocation/files (v1.3.3 or after) which will be useful. Also if you could capture a logcat at the time it fails that would be very useful.

I have been using Mozilla only for the last 6 or so months and not seen this, do you know if it occurs during the OCID download or the Mozilla download.

**Comment by vanitasvitae** [comment]
lacells_gen sais

info: MCC Filter: 268,225,270,228,232,260,214,208,235,222,262,234,238,204
info: Keine MNC Filter, nehme alle Netzwerke
info: Die URL lautet [http://opencellid.org/downloads/?apiKey=dev-usr--63bb-41fd-9787-beb25c8904e4&filename=cell_towers.csv.gz] (gzip)
fail: unknown format (magic number a0d)
fail: unknown format (magic number a0d)
info: Gesamtzeit: 455 Millisekunden
info: Fertig.

Next I'll get a logcat...

**Comment by vanitasvitae** [comment]
01-02 23:24:23.069 12968 12968 D /SpiceManager.java:489: 23:24:23.069 main adding request to request queue
01-02 23:24:23.070 12968 12994 D /SpiceManager.java:286: 23:24:23.070 SpiceManagerThread 0 Sending request to service : CachedSpiceRequest
01-02 23:24:23.071 12968 12994 D /RequestProcessor.java:63: 23:24:23.070 SpiceManagerThread 0 Adding request to queue 7403889: CachedSpiceRequest [requestCacheKey=DownloadSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest@cd83887] size is 0
01-02 23:24:23.071 12968 12994 D /RequestProcessor.java:85: 23:24:23.071 SpiceManagerThread 0 Adding entry for type class org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest$Result and cacheKey DownloadSpiceRequest.
01-02 23:24:23.071 12968 12994 D /RequestProgressManager.java:61: 23:24:23.071 SpiceManagerThread 0 Request was added to queue.
01-02 23:24:23.072 12968 12994 D /SpiceServiceListenerNotifier.java:146: 23:24:23.072 SpiceManagerThread 0 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.072 12968 12994 D /RequestProgressManager.java:82: 23:24:23.072 SpiceManagerThread 0 Sending progress PENDING
01-02 23:24:23.073 12968 12994 D /SpiceServiceListenerNotifier.java:146: 23:24:23.072 SpiceManagerThread 0 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.073 12968 13017 D /DefaultRequestRunner.java:83: 23:24:23.073 Thread-363 Processing request : CachedSpiceRequest [requestCacheKey=DownloadSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest@cd83887]
01-02 23:24:23.074 12968 12994 V /SpiceService.java:506: 23:24:23.073 SpiceManagerThread 0 Pending requests : 1
01-02 23:24:23.074 12968 13017 D /DefaultRequestRunner.java:129: 23:24:23.074 Thread-363 Cache content not available or expired or disabled
01-02 23:24:23.075 12968 13017 D /DefaultRequestRunner.java:148: 23:24:23.075 Thread-363 Calling netwok request.
01-02 23:24:23.075 12968 13017 D /RequestProgressManager.java:82: 23:24:23.075 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.076 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.076 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.078 12968 12994 V /SpiceService.java:508: 23:24:23.074 SpiceManagerThread 0 Stop foreground
01-02 23:24:23.094 12968 13017 D /RequestProgressManager.java:82: 23:24:23.093 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.094 12968 12968 D /SpiceServiceListenerNotifier.java:175: 23:24:23.093 main Processing request added: CachedSpiceRequest [requestCacheKey=DownloadSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest@cd83887]
01-02 23:24:23.095 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.095 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.095 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.094 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@8b363b4
01-02 23:24:23.097 12968 13017 D /RequestProgressManager.java:82: 23:24:23.097 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.097 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.097 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.097 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.097 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.100 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.099 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.101 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.100 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.109 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.108 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.109 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.109 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.110 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.110 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.111 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.110 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.192 12968 13017 D /RequestProgressManager.java:82: 23:24:23.192 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.193 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.193 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.194 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.194 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.195 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.195 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.502 12968 13017 D /RequestProgressManager.java:82: 23:24:23.502 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.503 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.503 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.503 12968 13017 W System.err: java.io.IOException: unknown format (magic number a0d)
01-02 23:24:23.503 12968 13017 W System.err: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:109)
01-02 23:24:23.503 12968 13017 W System.err: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
01-02 23:24:23.503 12968 13017 W System.err: 	at org.fitchfamily.android.gsmlocation.data.SourceConnection.<init>(SourceConnection.java:56)
01-02 23:24:23.503 12968 13017 W System.err: 	at org.fitchfamily.android.gsmlocation.data.Source.connect(Source.java:51)
01-02 23:24:23.504 12968 13017 W System.err: 	at org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest.getData(DownloadSpiceRequest.java:337)
01-02 23:24:23.504 12968 13017 W System.err: 	at org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest.loadDataFromNetwork(DownloadSpiceRequest.java:241)
01-02 23:24:23.504 12968 13017 W System.err: 	at org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest.loadDataFromNetwork(DownloadSpiceRequest.java:53)
01-02 23:24:23.504 12968 13017 W System.err: 	at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(CachedSpiceRequest.java:48)
01-02 23:24:23.504 12968 13017 W System.err: 	at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:150)
01-02 23:24:23.504 12968 13017 W System.err: 	at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
01-02 23:24:23.504 12968 13017 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
01-02 23:24:23.504 12968 13017 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-02 23:24:23.504 12968 13017 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-02 23:24:23.504 12968 13017 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-02 23:24:23.504 12968 13017 W System.err: 	at java.lang.Thread.run(Thread.java:818)
01-02 23:24:23.504 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.504 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.505 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.505 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.507 12968 13017 D /RequestProgressManager.java:82: 23:24:23.507 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.508 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.508 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.511  1888  1902 D WifiService: releaseWifiLockLocked: WifiLock{DownloadSpiceRequest type=1 binder=android.os.BinderProxy@98ab55a}
01-02 23:24:23.514 12968 13017 D /RequestProgressManager.java:82: 23:24:23.514 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.515 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.515 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.517 12968 13017 D /RequestProgressManager.java:82: 23:24:23.517 Thread-363 Sending progress LOADING_FROM_NETWORK
01-02 23:24:23.518 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.518 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 23:24:23.519 Thread-363 An exception occurred during request network execution :unknown format (magic number a0d)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: java.io.IOException: unknown format (magic number a0d)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:109)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at org.fitchfamily.android.gsmlocation.data.SourceConnection.<init>(SourceConnection.java:56)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at org.fitchfamily.android.gsmlocation.data.Source.connect(Source.java:51)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest.getData(DownloadSpiceRequest.java:337)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest.loadDataFromNetwork(DownloadSpiceRequest.java:241)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest.loadDataFromNetwork(DownloadSpiceRequest.java:53)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(CachedSpiceRequest.java:48)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:150)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-02 23:24:23.519 12968 13017 E /DefaultRequestRunner.java:154: 	at java.lang.Thread.run(Thread.java:818)
01-02 23:24:23.520 12968 13017 D /RequestProgressManager.java:82: 23:24:23.520 Thread-363 Sending progress COMPLETE
01-02 23:24:23.521 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.520 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.523 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.521 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.525 12968 13017 V /RequestProgressManager.java:161: 23:24:23.525 Thread-363 Removing CachedSpiceRequest [requestCacheKey=DownloadSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest@cd83887]  size is 1
01-02 23:24:23.528 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.528 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.529 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.529 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.530 12968 13017 D /RequestProgressManager.java:91: 23:24:23.526 Thread-363 Sending all request complete.
01-02 23:24:23.530 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.530 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.531 12968 13017 V /SpiceService.java:495: 23:24:23.531 Thread-363 Pending requests : 0
01-02 23:24:23.532 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.531 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.533 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.533 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@dfa7bdd
01-02 23:24:23.535 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.534 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.535 12968 13017 D /SpiceServiceListenerNotifier.java:146: 23:24:23.535 Thread-363 Message queue is Handler (android.os.Handler) {a4080c4}
01-02 23:24:23.536 12968 13017 D /DefaultRequestRunner.java:295: 23:24:23.535 Thread-363 It tooks 462 ms to process request CachedSpiceRequest [requestCacheKey=DownloadSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.gsmlocation.async.DownloadSpiceRequest@cd83887].
01-02 23:24:23.538 12968 12968 V /DefaultRequestListenerNotifier.java:131: 23:24:23.535 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@6fd0720
01-02 23:24:23.544 12968 12968 V /DefaultRequestListenerNotifier.java:135: 23:24:23.544 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.545 12968 12968 V /DefaultRequestListenerNotifier.java:166: 23:24:23.545 main Notifying 1 listeners of request failure
01-02 23:24:23.546 12968 12968 V /DefaultRequestListenerNotifier.java:172: 23:24:23.545 main Notifying UpdateDatabaseFragment_
01-02 23:24:23.567 12968 12968 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

**Comment by n76** [comment]
Looks like it is failing in the gzip library while reading from OpenCellID... They only allow one download a day and I am not sure what data they send after the first attempt. Is this on the first attempt after waiting at least 24 hours? If not then they could be sending some non-gzip data which is causing an issue on decode.

**Comment by vanitasvitae** [comment]
Its not the first attempt today. Another attempt failed before, but I don't have logs of this.

**Comment by n76** [comment]
I was able to duplicate it by doing a second attempt to load from OCID. I guess we could be a bit smarter about getting bad data from them and giving a useful message.

In the meantime, it seems that the Mozilla project is pulling tower data from OCID so the data you get from them is a superset so you might want to try just using that source.

**Comment by vanitasvitae** [comment]
Okay, i'll go for that source then ;)
