### ISSUE TITLE
location consistently wrong (with solution) / bad priority in backend

### ISSUE THREAD

**Issue by yepyepyep4711** [n76/Local-GSM-Backend#56]
Hello everyone,

since it took me several days to find out (until starting this post, to be exact), I thought I'd share this with you.
For a week or two, I've had consistently bad readings in places I knew were fine before. The phone would see me roughly 600m to the west and 200m to the south of where I was while using network location. I knew the problem was not the map app, since with GPS the location was correct. I updated dbs several times in several ways, to no avail.
And then, a few minutes ago, I thought of turning the old GSMNetworkLocationProvider off. Tadaaa! Problem fixed. I can recreate the problem each time by turning it on again.
So what must have happened is, the old GSMNetworkLocationProvider got prioritised over this backend (by UnifiedNlp?). No idea why, and I also can't find a way to change the behaviour, but since this backend get updates I just went and deleted the old one.
If you think there is no problem otherwise with the priority issue, you can close this.

Cheers

**Comment by n76** [comment]
Are you referring to https://f-droid.org/repository/browse/?fdfilter=unified&fdid=org.gfd.gsmlocation

**Comment by yepyepyep4711** [comment]
yes, exactly

**Comment by n76** [comment]
Then perhaps a bug reported to that backend project would be a good idea.

**Comment by yepyepyep4711** [comment]
last update in April 2014, "Warning: This app drains battery and seems no longer maintained.". Should the report go to that project or to the Unified NLP for the prioritisation issue?

**Comment by n76** [comment]
For prioritization, the UnifiedNLP project would be the place to file the bug. If I recall correctly, there is or was an issue posted regarding prioritizing backends a while back. You might want to see if that is still active.

**Comment by yepyepyep4711** [comment]
yep. Found it. Done. Thx and gn8!
