### ISSUE TITLE
Post notification when connected to an unknown tower

### ISSUE THREAD

**Issue by utack** [n76/Local-GSM-Backend#59]
Posting a notification when the phone is connected to a tower not in the database would help
- To warn about IMSI-catchers. Could be confused with new towers, but the user can decide to avoid these in doubt
- To help finding newly installed towers and contribute to the database, if the notification comes up in the same location are more than once
- To remind that the current location is not in the database, for example if MCC is not found display "region not in database"

Maybe you can think about it. The IMSI catcher aspect is outside of the scope of this app, but it would really help if someone wants to contribute and report a new cell tower. The "region not in database" message should be useful in any case.

**Comment by zoff99** [comment]
+1 sound like a nice feature

**Comment by Mannshoch** [comment]
Maybe work together with Mozilla Stumbler

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
