### ISSUE TITLE
Download per-country csv at import

### ISSUE THREAD

**Issue by wvengen** [n76/Local-GSM-Backend#6]
To make updating the database easier, I've created a [repository](https://github.com/wvengen/lacells) with lacells csv files per mcc, which is updated daily. Including a [small website](http://wvengen.github.io/lacells/).

It would be useful to have the app import directly from there. Something like a list of checkboxes with mcc codes and country names (e.g. like the osmand~ map selection screen).

Ideally I'd like to host this with a database, so that the app could request updates from the last time it was updated. But for now, this would already be a step forward.

**Comment by n76** [comment]
The two current data sources require a bit more than just a URL: OpenCellID needs an API code while Mozilla does dynamic naming of the file.

Would adding a new download source where the user specified the URL be sufficient for you?

**Comment by wvengen** [comment]
Technically, yes.

But I'd like to see Local-GSM-Backend becoming easier to use, without needing to understand API keys, URLs or MCC codes necessarily. To make privacy more accessible. Do you agree that would be an improvement?

**Comment by n76** [comment]
The suggestion then would be to drop any direct download from OpenCellID and possibly Mozilla and load only from a GitHub repository like you set up. And to avoid confusion with MCC codes build in a country to MCC lookup mechanism.

Taking it a bit further, we'd need to assure that the data on the repository was updated periodically, probably at least once a month. And it would be nice to let the user know that an update was available.

Does this match your vision?

**Comment by wvengen** [comment]
Yes, something like that. Does it align with your vision?

I could imagine direct OpenCellID and Mozilla download still being accessible from secondary button or menu option somewhere, if there's any demand for it.

The repository I mentioned is updated daily with downloads from OpenCellID and Mozilla. I've had contact with OpenCellID to ask if they are ok, which they are (it's within their CC license anyway; Mozilla was on Cc but I haven't heard anything from them - their license is public domain). Oh, you already got that :)

Updates to the database could be done currently by saving a commit-ish and downloading updated lines from the git repository - but I think a database-driven website would be more suitable for that. Need to find a place to host it then.

Perhaps both MCCs and countries might be displayed to the user, with initially the currently phone-detected MCC being selected. Some countries have multiple MCCs (e.g. U.S.) with big files. If their areas mostly overlap, I think we'd best select per-country, if their areas are different, it'd be better to name them by area to a have more fine-grained region selection. Note that I'm already building a [country-mcc csv index](https://github.com/wvengen/lacells/blob/gh-pages/lacells-countries.csv), with [this list](https://github.com/wvengen/lacells-creator/blob/master/mccs.csv) based on Wikipedia data.

Thanks for being open to this!

**Comment by yepyepyep4711** [comment]
being able to check "Europe" or "UK, France and Germany" like in OSMAnd~ would be so great

**Comment by UnknownUntilNow** [comment]
It is currently not possible to use this because the url schema http://wvengen.github.io/lacells/lacells-mcc_[mcc].csv is not working for 262 and 310 because there are multiple files with different postfixes (_a, _b, _c).

**Comment by wvengen** [comment]
@UnknownUntilNow Given enough interest, I could put the lacells files on a server that allows larger filesizes.

**Comment by n76** [comment]
@wvengen I will be releasing a version of the backend that will load from your repository. Does github allow for gathering metrics to see how popular that option becomes? It might help you gauge interest.

If you do move the files to a different server, please let me know so that I can change the URL stored in the backend.

**Comment by n76** [comment]
Implemented in v1.3.0

**Comment by wvengen** [comment]
@n76 nice!
I see the following options:
* Find a better place to host these files. Please let me know if you have ideas.
   (250 files of 10-150MB updated daily, preferably a stable public service)
* When the CSV can't be found, look for `_a` then `_b` etc.
* Add a json (or whatever) file listing the available countries with CSV files to read.

**Comment by UnknownUntilNow** [comment]
currently the _a and _b is hardcoded for some MCC. It would be a good idea to add them for exanple to <https://github.com/wvengen/lacells/blob/gh-pages/lacells-countries.csv>.

**Comment by wvengen** [comment]
@UnknownUntilNow Cool :) I see you're reading the countries.csv file already. Shall I add a a single column with space-separated urls, or shall I add a `url_count` as well as `url_1`, `url_2` etc. columns?

**Comment by UnknownUntilNow** [comment]
To my mind a single column with space-separated urls is better.

**Comment by wvengen** [comment]
:+1:

**Comment by UnknownUntilNow** [comment]
added this at https://github.com/UnknownUntilNow/Local-GSM-Backend/commit/7a3d19d5f438d84afe787a7d63d9a4c7f0b5a5bf (but until there is a "urls" column ...)

**Comment by wvengen** [comment]
Allright, [here](https://github.com/wvengen/lacells/blob/gh-pages/lacells-countries.csv)'s the "urls" column. It's a relative url, to keep things compact and not require specifying the full url somewhere in the lacells-creator configuration. I hope you don't mind adding url resolving (since it might become a full url at some point, e.g. when different repositories would be used).
