### ISSUE TITLE
Add Wifi support

### ISSUE THREAD

**Issue by amilopowers** [n76/Local-GSM-Backend#61]
First let me thank you for your great job!

I would love to have the option download Wifis from Mozilla Location Service as well. When abroad Wifis improve location accurancy a lot.

**Comment by n76** [comment]
Mozilla Location Services does not allow downloads of WiFi data, so this request is not possible to fulfill.

There is an issue/enhancement request for being able to import/export WiFi AP information including that from radiocells.org / openbmap.org That enhancement is being worked on and once that is available, one could pre-load the WiFi APs for the area to be visited. See: https://github.com/n76/wifi_backend/issues/28
