### ISSUE TITLE
Stopped working after 1.3.6 update

### ISSUE THREAD

**Issue by sobrus** [n76/Local-GSM-Backend#63]
Hi, unfortunately GSM backend stopped working on my phone with 1.3.6 update from F-Droid.
(Asus ZF5, Android 4.3, unifiedNlp 1.6.2-dirty from F-Droid)

Same tower, same database (and tower present in database, checked using CellID and sqlite).

1.3.4 works OK, 1.3.6 - no location

(I've checked several times upgrading and downgrading apk)

**Comment by n76** [comment]
Is this the same issue as reported in https://github.com/n76/Local-GSM-Backend/issues/62

Can you check your logcat and see if it is related to permission issues or broken pipes when trying to access the database?

**Comment by sobrus** [comment]
adb logcat | grep NlpLocationBackendFuser

gives no information at all

I've checked "| grep Nlp" but even then logs are very scarce.
[log.txt](https://github.com/n76/Local-GSM-Backend/files/190577/log.txt)
