### ISSUE TITLE
NullpointerException after disabling flightmode 

### ISSUE THREAD

**Issue by khrise** [n76/Local-GSM-Backend#64]
On my device (S5-Mini, cm 13.0), version 1.3.6 goes down with a NullpointerException immediately after flightmode gets disabled.
To reproduce, enable flightmode, disable flightmode.

Logcat shows:
`03-30 11:12:22.445 E/AndroidRuntime(21665): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.location.Location.setTime(long)' on a null object reference
03-30 11:12:22.445 E/AndroidRuntime(21665): at org.fitchfamily.android.gsmlocation.GsmService$1$1.doIt(GsmService.java:76)
03-30 11:12:22.445 E/AndroidRuntime(21665): at org.fitchfamily.android.gsmlocation.GsmService$1$1.onServiceStateChanged(GsmService.java:84)
03-30 11:12:22.445 E/AndroidRuntime(21665): at android.telephony.PhoneStateListener$2.handleMessage(PhoneStateListener.java:280)
03-30 11:12:22.445 E/AndroidRuntime(21665): at android.os.Handler.dispatchMessage(Handler.java:102)
03-30 11:12:22.445 E/AndroidRuntime(21665): at android.os.Looper.loop(Looper.java:148)
03-30 11:12:22.445 E/AndroidRuntime(21665): at org.fitchfamily.android.gsmlocation.GsmService$1.run(GsmService.java:101)`

**Comment by n76** [comment]
I am able to duplicate this. Thank you for reporting it. I've been a bit busy recently but I hope to be able to fix this and at least one of the other outstanding reports in the next week or so.

**Comment by khrise** [comment]
Wow, that was quick - thanks!
