### ISSUE TITLE
Resume partial download

### ISSUE THREAD

**Issue by RalfJung** [n76/Local-GSM-Backend#65]
I often have quite some trouble updating the GSM database. What happens is that I start the download, which takes around 20 to 30min. At some point, the WiFi connection is flaky enough to fail, and the download cancels -- and I have to start all over again. I just got the third failure in a row, which is fairly frustrating. It'd be great if the partial download could somehow be completed.

**Comment by licaon-kter** [comment]
Or you get a call or you open another app by mistake or the moon aligns with Venus, you can't do anything at all 'cause the download is cancelled.

Why can't it work in background just like the other apps do?

**Comment by n76** [comment]
It actually does work in the background (as you can tell by watching with logcat). But for some reason, the UI does not always reconnect with the background thread so you think it has stopped.

I've been unsuccessful in figuring out why the UI is flakey on reconnecting to get status from the background. . .

**Comment by licaon-kter** [comment]
Ok, so this stays.

For starters, at least you can detect it's still running so you can replace `Download now` with 'Download in progress please wait' ?

The notification has actual text or?

**Comment by licaon-kter** [comment]
In the mean time, you can use a local terminal (eg. [Termux](https://github.com/termux/termux-app)) to watch for progress:
` cd /sdcard/Android/data/org.fitchfamily.android.gsmlocation/files/ ; tail -f lacells_gen.log`

**Comment by n76** [comment]
Closing this as there does not appear to be a good way to resume a failed download.

Specifically, the data being downloaded are in very large zip format files and to save space and make this possible on phones with limited storage the files are unzipped and CSV value records extracted in a pipeline without actually saving the original ZIP or intermediate CSV files. If a data connection failure occurs we really don't know where we are in the ZIP file so have no good way to later resume.

**Comment by licaon-kter** [comment]
Do at least add some info on screen explaining that it might continue in the background and how to check, say like my post above.
