### ISSUE TITLE
Location Area - Australia selected as Norfolk Island

### ISSUE THREAD

**Issue by MobileXUser** [n76/Local-GSM-Backend#68]
In the Areas selection menu when Australia is selected automatically Norfolk Island is selected and Australia does not appear in the selected areas.

**Comment by n76** [comment]
According to https://en.wikipedia.org/wiki/Mobile_country_code the mobile country code for both Australia and Norfolk Island is 505. So it should be functionally working, just always displaying Norfolk Island when displaying.

I'll drop Norfolk Island from the list of countries as it has a much lower population.
