### ISSUE TITLE
MLS contains the same data as OCID

### ISSUE THREAD

**Issue by agilob** [n76/Local-GSM-Backend#69]
Mozilla has an agreement with OCID to exchange data on a monthly(?) basis, so MLS contains the same data as OCID. It's pointless to support both services now.
https://location.services.mozilla.com/stats

**Comment by n76** [comment]
True. And in fact, I have not been pulling from OCID for a while, just using Mozilla.

But the option is entirely up to the user as to which boxes they check when setting up their copy of the backend and there is not really a compelling reason to drop the functionality.

**Comment by agilob** [comment]
The reason is that user thinks that using both services and downloading data from both of them for 7 hours (for me) will provide more accurate location, which is not true. This behaviour is misleading, maybe instead using checkbox it should provide radiobox?
