### ISSUE TITLE
Location lost after a few seconds

### ISSUE THREAD

**Issue by Isgar** [n76/Local-GSM-Backend#70]
Reproduction steps:

- start Osmand
- see position provided by LocalGSMBackend
- wait 10 seconds (sometimes instantly?)
- location disappears until restarting Osmand

Catlog shows this every few seconds:
` V/NlpLocationBackendFuser( 5831): Ignoring location update as it's older than other provider. `

Additional info:

- Mozilla backend works fine, therefore I think this backend causes the problem
- some apps rarely ever get the location
- database update and reboot did not help
- I don't remember when it started and what changed, but it was working a couple of months ago
- using all newest versions from F-Droid

**Comment by okias** [comment]
I also noticed bug, but didn't realized this is GSM backend bug :) Thank you for report & fix!! :+1:

**Comment by n76** [comment]
Not sure if it could officially be classified a bug, a API not fully documented or a left over debug logging statement after the change that added times to the reports. But is was annoying.

**Comment by Isgar** [comment]
Thank you for the quick fix, but it doesn't solve the actual problem. I still have the same issue with 1.4.2.

In contrast, it seems to have gotten worse. Now I don't even get the initial position anymore.

**Comment by n76** [comment]
Getting initial position should be unrelated to the `Ignoring location update as it's older than other provider` message problem.

Perhaps you have the same issue as @tastytea reports: https://github.com/n76/Local-GSM-Backend/issues/71

If you install the version I put out for him, we could get some logging that will tell me more about why you are not getting even an initial position.

**Comment by Isgar** [comment]
1.4.3 fixed it for me, thank you!
