### ISSUE TITLE
Download not work correct

### ISSUE THREAD

**Issue by Mannshoch** [n76/Local-GSM-Backend#73]
After a log time download The program tells me he has no database. The app setting tells me an use of 6.5GB.
v. 1.4.4

**Comment by n76** [comment]
Do you have a file browser (or even ability to su in adb shell)? If so, can you get me the log file that should be at /sdcard/Android/data/org.fitchfamily.android.gsmlocation/files/lacells_gen.log

Also a listing of what in that directory could be useful.

**Comment by n76** [comment]
At least on your last attempt (which the log file covers) it appears that the indexing started.

After indexing, the expected operations are:

1. Close database
2. Remove journal file
3. Rename file to lacells.db.new

It appears that those steps did not occur on your phone for any of your three tries.

Looking at the code, the only place I can see this failing should have created an exception and thus a stack trace in your logcat at the time this occurred. If you can catch this in the act, it would be nice to see the logcat if/when that occurs.

As a work around for now, you can rename the most recent new_lacells*.db file to lacells.db.new and remove the other two .db files and remove the new_lacells*.db-journal files.

**Comment by Mannshoch** [comment]
could be closed. 
I got this ticket out of my eye. Now every thing work.
Thanks for your help.
