### ISSUE TITLE
Database creation stops if phone rotated

### ISSUE THREAD

**Issue by xenithorb** [n76/Local-GSM-Backend#74]
During the long process of creating the db, if you rotate the phone, the progress stops and the app asks you to create it again.

**Comment by n76** [comment]
DB downloading/creating is actually still happening in the background. Unfortunately, I've been unable to determine why the display is not always able to reconnect to the background service and thus asks you to create it again.

I'm leaving this report open to remind me to look at that again.

**Comment by takiainen** [comment]
Any news regarding this issue? It's rather frustrating to try to create the database with the app - majority of times it fails. It fails if the screen accidentally shuts off, you rotate the phone or just switch to another app.

**Comment by tomikmar** [comment]
I had similar problem. The app behaved strange when:
* I rotated screen (but after short time interface picked up progress)
* phone went to sleep mode and I had to unlock my phone

Here is the screenshot:
![screenshot_20170810-221553a](https://user-images.githubusercontent.com/5788375/29191721-f5b992c4-7e1e-11e7-9e70-df9e14ec7186.png)

**Comment by xenithorb** [comment]
@n76 ping?

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
