### ISSUE TITLE
Ability to use multiple database files.

### ISSUE THREAD

**Issue by yuphorian6** [n76/Local-GSM-Backend#77]
A single lacells.db approach limits using multiple databases.

I'm thinking the app needs to be able to read from multiple db files (with priority) so users can use better databases.

Like for example,

cells_mozilla_mccAAA_mnc111.db
cells_mozilla_mccAAA_mnc222.db
cells_opencellid_mccAAA_mnc111.db
cells_opencellid_mccAAA_mnc222.db
....

And have a setting whether to give more priority to mozilla or opencellid..
isolation of database with filters mozilla, opencellid, mcc, mnc will be useful i think.

Could be better titled isolation of databases.. Sorry

**Comment by n76** [comment]
I have handed off this project to @devee. The new official repository for this work is a now at https://gitlab.com/deveee/Local-GSM-Backend.

If this is still an issue, please open it on the new repository with the new maintainer.
