### ISSUE TITLE
@wvengen database isolation..

### ISSUE THREAD

**Issue by bharat226g** [n76/Local-GSM-Backend#78]
AFAIK , @wvengen database contains cell data aggregated from both mozilla and opencellid. 

When I use database downloaded from @wvengen , the location is not very accurate (maybe because it has conflicting results from mozilla and opencellid). I was inaccurate by about 5km. I downloaded the mozilla data alone from pc and generated the mozilla-only database, which gave accurate location results.

So, I'm thinking it is better to isolate mozilla and opencellid databases from @wvengen . I mean he will need to generate separate databases for both mozilla and opencellid.

cells_mozilla_mccXXX.csv
cells_opencellid_mccXXX.csv
to be used as separate db files. Useful along with #77

I also request @wvengen to create mnc per mcc databases , so one can download much lesser database.
Like,
cells_mozilla_mccAAA_mnc111.csv
cells_mozilla_mccAAA_mnc222.csv
cells_opencellid_mccAAA_mnc111.csv
cells_opencellid_mccAAA_mnc222.csv

Since, getting all mnc's in a mcc is pointless for individual phones, as simcards/network are not changed often.

**Comment by wvengen** [comment]
@bharat226g thanks for the issue. I'm thinking we can choose the most precise instead of merging them (or those with most measurements, or something more complicated).

I like the mnc/mcc idea, especially if we can get from the phone which ones are useful.

**Comment by bharat226g** [comment]
I think one will not be more precise over the other in all world locations, atleast previously.
But since both services are exchanging data, it might be ok using mozilla data alone, since it has data from ocid and no api key is required.

I'm ok with mozilla data alone. But thinking that users might be inclined to using ocid as well, i requested to isolate them.

Also this database generation to mcc_mnc level will benefit phone users a lot. 
Along with #79 requested feature, user can download a very small sized database (that's only relevant to his phone) much easily.

**Comment by wvengen** [comment]
I like your idea of separating them. We may be able to provide checkboxes to enable one or both as an advanced option. The default could then provide the more complete source.

I have no clue actually how much their coverage overlaps or not, would be interesting to know. Indeed if they exchange data one is enough.

I'd be happy to merge suitable PRs in https://github.com/wvengen/lacells-creator :)

**Comment by radioxoma** [comment]
Good point. I just compared OCI and MLS data in one town which I'm going to map and it was almost the same. Mozilla [explicitly notes](https://location.services.mozilla.com/downloads) that OCI data is used:

> The service incorporates aggregated cell data from our partner the OpenCellID project.

May be Mozilla augment own raw data before trilateration, I'm not sure.

**Comment by wvengen** [comment]
Thanks @radioxoma, I'll try to find some time to move to Mozilla-only for the lacells data.
