### ISSUE TITLE
cannot create database

### ISSUE THREAD

**Issue by takiainen** [n76/Local-GSM-Backend#82]
It seems to download everything from OpenCellID, but once everything is done, the backend says there is no database. Internal storage size is just 18MB.

I also had to enable all the permissions manually.

**Comment by n76** [comment]
Which data source are you using? Open Cell ID has had an issue with their ZIP files that causes the built in ZIP decode library on Android phones to fail. I've had no issues with the Mozilla version (which also contains all the OCID data as they have some sort of sharing agreement).

**Comment by takiainen** [comment]
I tried using opencellID only. But now I have created the database with fastlacellsgenerator, and everything is working normally (except database update I assume..).
