### ISSUE TITLE
Location very inaccurate

### ISSUE THREAD

**Issue by JonnyTech** [n76/Local-GSM-Backend#89]
I am struggling to get an accurate fix. Created database on the phone using the built-in tool with both sources selected. But location is out by several km. Not sure if linked to #71 as I too have dual sim (one for calls and texts and one for data). What can I provide to help debug this problem? Running CM13.1 with latest testing microg. Willing to provide whatever assistance required.

**Comment by gdt** [comment]
Several km off for GSM is not really wrong.  Perhaps you are in the city with cell sites every 100m.   But out in the country they are 5-10 km apart.

To debug, you'll have to see what your phone is reporting for cell site (use satstat to see), and also adb logcat from the location provider to see what it is looking up, and then look up that data in the online databases that you used, and see what it says. 

There is probably a larger issue with whether your phone reports cellids from both sims, and also the cells it is tracking but not using, and associated strengths, and then whether localgsmbackend is fusing all of this.

For extra credit, you can go find where the cell site actually is (see the radiocells wardriving app RadioBeacon, currently gettting renamed, or some similar one, or just look at satstat and climb the gradient).  Also add the cell antennas to openstreetmap.

**Comment by JonnyTech** [comment]
I am in a built up area with masts all around.

![gsm](https://cloud.githubusercontent.com/assets/3584732/21084982/4733c8de-c003-11e6-9d55-38af5fd85825.png)

How do I get a logcat?

What is "climb the gradient" and add the antenna info?

Thanks

**Comment by gdt** [comment]
logcat: https://wiki.cyanogenmod.org/w/Doc:_debugging_with_logcat

climb the gradient: look at the strongest signal, and then move to other locations nearby to see if you can get higher numbers for signal strength.   Note that -43 is higher (stronger) than -47.   But -47 dBm is very very strong, indicating you are probably 10-50m from antennna with direct line of sight.

Overall, look up 234/10/21579/cellid in the various databases and see what coordinates are stored.

adding to openstreetmap:  https://openstreetmap.us/start-mapping/ https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dantenna
