### ISSUE TITLE
Update OpenCellID/MLS database

### ISSUE THREAD

**Issue by breversa** [n76/Local-GSM-Backend#9]
Hi there,

The option to generate a OpenCellID/MLS database is nifty though a bit tedious because slow.

Is there any way to update the database without having to build it again from scratch ? I'm thinking of MLS in particular, as Mozilla publishes hourly diffs (https://location.services.mozilla.com/downloads) for the last 3 days.

(I realise this is relevant mainly for "power users"/contributors (I use MozStumbler) who want to check if their work has been aggregrated yet.)

**Comment by n76** [comment]
The main intent of the built-in database creation was to allow the backend to be used by non-power users.

As a power user, take a look at either the gen_lacells or gen_lacells_merged scripts at https://github.com/n76/lacells-creator they do the same job as the built in database creation. And, at least on my laptop, run much faster than the built-in does on my Galaxy Nexus.

You can use them as a base for creating your own script(s) that could take add hourly diffs to a an existing database.

I haven't tried it, but you might even be able to run the scripts on the phone via a terminal app. Not sure if wget exists on the phone though. If that works it would mean that you would not need to haul around a computer with you when you want to check your contributions.
