### ISSUE TITLE
error initializing backend

### ISSUE THREAD

**Issue by jonno2002** [n76/Local-GSM-Backend#94]
using a nexus 5 with lineage os 14.1 (android 7) and cant get the location backend to work, ive tried installing it in the priv-app folder and still doesnt help. it happens under unifiednlp settings, under configure location backends, when i try tick the box to enable it, it brings up "error initializing backend"

i have another nexus 5 with cyanogenmod 13(android 6) on it and that works fine

any help would be great

**Comment by n76** [comment]
A logcat from the the crash would be very helpful.

**Comment by jonno2002** [comment]
this is what comes up as im trying to enable the backend, i went into privacyguard and allowed course location but still brings up same error.

```
02-17 12:10:43.773   795   825 I ActivityManager: Displayed com.google.android.gms/org.microg.gms.ui.SettingsActivity: +129ms
02-17 12:10:47.738   795   988 I ActivityManager: START u0 {cmp=com.google.android.gms/org.microg.nlp.ui.SettingsActivity} from uid 10079 on display 0
02-17 12:10:47.886   795   825 I ActivityManager: Displayed com.google.android.gms/org.microg.nlp.ui.SettingsActivity: +135ms
02-17 12:10:47.911 10296 10325 D OpenGLRenderer: endAllActiveAnimators on 0x99c2f680 (ListView) with handle 0x9b558710
02-17 12:10:59.941   795  1626 W ActivityManager: Permission Denial: Accessing service ComponentInfo{org.fitchfamily.android.gsmlocation/org.fitchfamily.android.gsmlocation.GsmService_} from pid=10296, uid=10079 requires android.permission.ACCESS_COARSE_LOCATION
02-17 12:11:01.966   795   795 W WindowManager: Attempted to remove non-existing token: android.os.Binder@b43eafc

```

**Comment by n76** [comment]
It hasn't been given permission to access course locations (i.e. get list of mobile/cell towers the phone is detecting). In the system app settings give the backend all permissions it asks for. The bug here is that it should have detected the lack of permission and asked to have it granted. I will look into that when I get a phone setup with Nougat.

**Comment by jonno2002** [comment]
changed permissions in "apps" to allow location, same error still, tried rebooting, same error still

**Comment by jonno2002** [comment]
i figured it out, had to go into "microg settings" and under "self-check" i had to tick 4 boxes under "permissions granted"
thanks for the help
