### ISSUE TITLE
Resuming and pausing database download + estimate

### ISSUE THREAD

**Issue by Avamander** [n76/Local-GSM-Backend#95]
I'd really love if it downloaded the cell list first, thus providing a way to pause-resume the progress and after it has been downloaded it starts creating the database. In addition to the enormous time it takes  currently any network errors make it fail thus lengthening the process even more.

**Comment by n76** [comment]
The current cell list is in a .zip file nearly 500MB in size, unzipped it is about 1.68 GB. For many phones it is not feasible to download all that prior to scanning the data to load select records into a database. Thus the backend pipes the download stream through a unzip and a csv decoder on the fly.

If you are experiencing too many network errors with generating the database on the phone, then you can use the offline scripts to generate the database on your desktop or laptop and then copy the database to the phone.

**Comment by Avamander** [comment]
Could you please provide that option (even more so when db location is set
to SD card)? In addition to the storage, I would also prefer quick download
and then offline processing instead of waiting three hours anchored to
internet. And for estimated time the full downloading is not even needed.

**Comment by n76** [comment]
If I receive a pull request that has a reasonable implementation I will consider it.

**Comment by Avamander** [comment]
"Reasonable implementation" is rather ambiguous. If full download through the app is something you never wish to implement could you make it possible to import the manually downloaded data into the app (thus leaving downloading for example to Android download manager).
