### ISSUE TITLE
OpenCellId

### ISSUE THREAD

**Issue by Gitschubser** [n76/Local-GSM-Backend#96]
http://wiki.opencellid.org/wiki/Main_Page

**Comment by Laicure** [comment]
> _TL-DR; [Unwired Labs](https://unwiredlabs.com/?ref=ocid) has taken over maintainership of OpenCelliD. The main website will be down till 12AM GMT on Thursday 20th April while we set things up. Registrations are paused, but all APIs are functional._

So I tried using this back-end **using** their _token_...
Didn't work; **Incorrect API Key**

**Comment by utack** [comment]
I am not getting anywhere either, can't build a database even with my new api key

**Comment by LibertatisPrius** [comment]
I am also unable to set the API key. I get "The given API key is incorrect. Enter a valid one (or disable the OpenCellID data source)." when I try to enter my token.

**Comment by IrrationalEscalation** [comment]
The download URL needs to be updated:

Old URL EG:
`http://opencellid.org/downloads/?apiKey=a12b3456-7cd8-901e-2345-67fa8bc90de&filename=cell_towers.csv.gz`

New URL EG:
`https://download.unwiredlabs.com/ocid/downloads?token=a12b3456-7cd8-901e-2345-67fa8bc90de&file=cell_towers.csv.gz`

**Comment by utack** [comment]
Thanks for fixing this, it works again

**Comment by KarmaMonk** [comment]
I'm not able to set the API Key: "The given API key is incorrect. Enter a valid one (or disable the OpenCellID data source)."
LocalGsmNlpBackend 1.4.14
LineageOS 14.1

**Comment by n76** [comment]
@KarmaMonk  - The new OCID people may well have changed the format of their API key which might break the validity checker. I know my several year old key works, but maybe the new ones are different. Could you send me a private message with the API key you are trying to use and I'll see what the issue is.
