### ISSUE TITLE
Update version of package on F-Droid

### ISSUE THREAD

**Issue by zeorin** [n76/Local-GSM-Backend#99]
Currently the version available in F-Droid is 1.4.9. The latest version tag on this repo is also 1.4.9. From F-Droid's wiki page for this package I gather that it updates based on version tags. Please could you push the latest version tags?

**Comment by n76** [comment]
Thank you for the reminder. I've pushed the tag for v1.4.14

**Comment by relan** [comment]
v1.4.15 tags wrong version: when I check out v1.4.15, build.gradle says this is 1.4.14. Same with v1.4.16. This mismatch breaks F-Droid's autoupdating. Please bump `versionName` and `versionCode` before tagging a new release.
